[package]
name = "zombodb"
description = "Making Postgres and Elasticsearch work together like it's 2022"
version = "3000.0.9"
edition = "2018"
build = "build.rs"
readme = "README.md"
license = "LICENSE.md"

[lib]
crate-type = [ "cdylib" ]

[features]
default = [ "pg14" ]
pg10 = [ "pgx/pg10", "pgx-tests/pg10" ]
pg11 = [ "pgx/pg11", "pgx-tests/pg11" ]
pg12 = [ "pgx/pg12", "pgx-tests/pg12" ]
pg13 = [ "pgx/pg13", "pgx-tests/pg13" ]
pg14 = [ "pgx/pg14", "pgx-tests/pg14" ]
pg_test = [ ]

[dependencies]
byteorder = "1.4.3"
chrono = "0.4.19"
crossbeam-channel = "0.5.2"
dashmap = "5.1.0"
humantime = "2.1.0"
indexmap = "1.8.0"
lalrpop-util = "0.19.7"
lazy_static = "1.4.0"
levenshtein = "1.0.5"
memoffset = "0.6.5"
num_cpus = "1.13.1"
pgx = { git = "https://github.com/zombodb/pgx.git", rev = "dc185530da5ef018938063f9226fa29a63b03a54" }
pgx-macros = { git = "https://github.com/zombodb/pgx.git", rev = "dc185530da5ef018938063f9226fa29a63b03a54" }
rayon = "1.5.1"
regex = "1.5.4"
rustc-hash = "1.1.0"
serde = { version = "1.0.136", features = [ "derive" ] }
serde_json = { version = "1.0.79", features = [ "preserve_order" ] }
serde_cbor = "0.11.2"
sqlformat = "0.1.8"
ureq = { version = "2.4.0", features = [ "json" ] }
url = "2.2.2"

[build-dependencies]
lalrpop = { version = "0.19.7", features = [ "lexer" ] }
built = { version = "0.5.1", features = [ "git2", "semver" ] }

[dev-dependencies]
pgx-tests = { git = "https://github.com/zombodb/pgx.git", rev = "dc185530da5ef018938063f9226fa29a63b03a54" }
libc = "0.2.118"

[profile.dev]
panic = "unwind"
debug = true
opt-level = 0

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1

